# Generated by Django 4.1 on 2022-09-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_size_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='title',
        ),
    ]
